### ISSUE TITLE
[Droid] Crash while Navigating after a Hot Reload

### ISSUE THREAD

**Issue by saamerm** [dotnet/Comet#174]
Hey Community! 

Let's work on stabilizing android too so we can make Comet truly cross-platform!
Navigation works on load, but if you make a change to some text, save, and then try to navigate, it will crash.

**Steps to Reproduce**
-------------
* I cloned the repository and opened the `Comet.sln` file in Visual Studio for Mac, and I switched to the `Comet.Android.Sample`. 
* I built it on the emulator and it worked great! I can tap on a row in the list view, and it goes to the detail page. Then I go back and that works fine too.
* Then I change the text in `MainPage.cs` from "Ride the Comet" to "Ride the Comets". 
* After I Save I can see hot reload working, but when I tap on any row in the ListView now, it crashes the app because of a Null Reference Exception.

**Exception Cause**
---------------------
* The exception is caught on this row:
![image](https://user-images.githubusercontent.com/8262287/73908355-628df500-4877-11ea-9a70-4ac57ca6f7a0.png)

**Possible cause**
---------------
* It's a little difficult to diagnose, but I believe it's because hot reload performs the Remove function and passes in a null action to SetPerformNavigate, but Im not sure
![image](https://user-images.githubusercontent.com/8262287/73908380-78031f00-4877-11ea-96e9-6af452392a2a.png)

**Comment by Clancey** [comment]
This shouldn't be an issue anymore. Re-open if it is.

**Comment by saamerm** [comment]
@Clancey Was it fixed in any commit/pull request?

**Comment by Clancey** [comment]
Honestly not sure, But I fixed all the crashes I ran into with HotReload, and a lot of things have changed drastically from the switch to Maui.
