### ISSUE TITLE
Deploy to net6 windows?

### ISSUE THREAD

**Issue by ToolmakerSteve** [dotnet/Comet#205]
As a long-time XF app dev, I would like to experiment with Comet.

I see that Getting Started doesn't mention deploy to net6.0-windowsXXX. Is this supported?

In VS 2022 Enterprise preview 6, I tried:
* Create new project using Comet template.
* Uncomment the TargetFramework windows line in .csproj.
* Changing Framework under "> Windows Machine" to net6.0-windows10.0.19041.

Result:
* C:\Program Files\dotnet\sdk\6.0.100-rc.2.21505.57\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(267,5): error NETSDK1005: Assets file 'C:\Users\toolm\source\repos\CometApp1\CometApp1\obj\project.assets.json' doesn't have a target for 'net6.0-windows10.0.19041'. Ensure that restore has run and that you have included 'net6.0-windows10.0.19041' in the TargetFrameworks for your project.

(OTOH, maybe I need to wait until Preview 7.  In Preview 6, I don't even get option to launch any MAUI project to Android Emulator. So I can't test there. FYI [Visual Studio 2022 impossible to open Android SDK Manager](https://developercommunity.visualstudio.com/t/visual-studio-2022-impossible-to-open-android-sdk/1547475).)

This is the project.assets.json that gets generated. After editing .csproj to add Windows TargetFramework, I did delete bin and obj folders, to re-generate this.
[project.assets.zip](https://github.com/dotnet/Comet/files/7406411/project.assets.zip)

**Comment by Clancey** [comment]
There are things missing from Maui. Windows, Those changes should be in for Preview 13
