### ISSUE TITLE
Can't Build Comet.sln on VS Enterprise 2022 Preview 6

### ISSUE THREAD

**Issue by ToolmakerSteve** [dotnet/Comet#206]
Simply attempting to open comet.sln leads to multiple error popups.

First one is "The XamarinShellPackage package did not load correctly." (This seems to be a fundamental problem with Preview 6. Not specific to Comet.)

Then when Build, get

> Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0234	The type or namespace name 'HandlerMauiAppBuilderExtensions' does not exist in the namespace 'Microsoft.Maui' (are you missing an assembly reference?)	Comet.Tests	C:\gh\Comet\tests\Comet.Tests\UI.cs	11	Active

Given that it is in Comet.Tests, I'll attempt to comment out the reference, and proceed.

**Comment by Clancey** [comment]
I have re-worked the solution. It now builds Maui from Source, which will prevent this from happening.
