### ISSUE TITLE
Missing properties on controls

### ISSUE THREAD

**Issue by davidortinau** [dotnet/Comet#221]
I'm missing a bunch of properties, some I've ping you about on Discord. I'm opening this issue to track it.

Today I'm missing
* Horizontal and Vertical layout options
* IsVisible
* IsEnabled
* Gestures aren't working everywhere I'd expect
* Shadows (method is there, but no shadow is drawn)

**Comment by Clancey** [comment]
Layout Options are there: `HorizontalLayoutAlignment` and `VerticalLayoutAlignment`

IsVisible is intentionally skipped, just use include or exclude it from the View

Just added IsEnabled

Fixed Shadows.

Gestures are missing from Core, I might be able to add them back into comet while we wait
