### ISSUE TITLE
[Android] ScrollView always is vertical

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/Comet#231]
Trying to create an horizontal ScrollView seems to not be working. 

```
new ScrollView(Orientation.Horizontal) { 
            
}
```
The sample: https://github.com/jsuarezruiz/comet-travel-app-challenge/blob/main/src/CometTravelApp/CometTravelApp/Views/HomeView.cs#L129

**Comment by Clancey** [comment]
Fixed 45c268a1c80d0c98789005b2accf38ecff7eaa82
