### ISSUE TITLE
Layout isn't responsive to window size changes

### ISSUE THREAD

**Issue by davidortinau** [dotnet/Comet#235]
<img width="1279" alt="Screen Shot 2022-01-15 at 9 48 47 AM" src="https://user-images.githubusercontent.com/41873/149628084-cc7a5a5a-04b7-48c5-a143-6255cf3e09f4.png">

**Comment by Clancey** [comment]
I'm am pretty sure this is a Maui.Core bug. But I will verify.

**Comment by Clancey** [comment]
Fixed with: a43d3516b66994a43fc0345270fa199fa20a1d25
