### ISSUE TITLE
Default template app home page Ride the comet text hides once reached end of screen horizontally

### ISSUE THREAD

**Issue by SarthakGz** [dotnet/Comet#240]
I run fresh app generated through template.On home page
If you click Ride the comet button too much time till the above label text reaches end of screen horizontally label gets hidden.
Though it should concatenate to next line.I tried to give stacklayout fillandexpand vertical but that also doesn't work.

**Comment by Clancey** [comment]
This is a Maui.Core bug. It happens only on android. Multiline, also doesnt work which would fix that...

**Comment by Clancey** [comment]
Opened: https://github.com/dotnet/maui/issues/4487
