### ISSUE TITLE
.NET MAUI Comet App template can't build - AndroidManifest bad path

### ISSUE THREAD

**Issue by JbmOnGitHub** [dotnet/Comet#250]
Thanks for Comet ! Unfortunately, I can't build the .NET MAUI Comet App template...

IDE : Microsoft Visual Studio Community 2022 (64 bits) - Version 17.2.0 Preview 5.0
I'm able to launch classic MAUI templates without issue. (on windows and android platforms)

I followed all the steps from https://github.com/dotnet/Comet/wiki/Getting-Started

After that, when i launch : dotnet new comet -n RideTheComet

I see this build error :
Erreur	XA1018	Specified AndroidManifest file does not exist: C:\Users\johndoe\source\repos\Comets\RideTheComet\RideTheComet\AndroidManifest.xml.	RideTheComet
C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.300-rc.2.27\tools\Xamarin.Android.Common.targets	520

(nb : if i move AndroidManifest file, i obtain many other errors about Xamarin dlls)

Thanks for any help you can give me to get started properly ! 🆘

**Comment by Clancey** [comment]
I need to update the doc. Install RC2. Instructions are here: https://github.com/dotnet/maui/blob/main/.github/DEVELOPMENT.md

**Comment by JbmOnGitHub** [comment]
Thanks for the instructions but when i execute  dotnet workload install maui (with RC2 parameters)

I see this error : 

microsoft.net.workload.mono.toolchain.manifest-6.0.300.msi.x64::6.0.5 not founded in NuGet https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-runtime-323bf2dd/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-emsdk-572aeedc/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json;https://api.nuget.org/v3/index.json

**Comment by JbmOnGitHub** [comment]
Thanks, i see this instructions : 
RC 2 branch

1. First, install .NET SDK 6.0.300 => https://dotnet.microsoft.com/en-us/download/dotnet/6.0 ; the page has a link to the SDK 6.0.201 in a 6.0.3 section (!)
2. Next run the following workload command:  dotnet workload install maui --from-rollback-file https://aka.ms/dotnet/maui/6.0.300/rc.2.json (...)

But i have this error =>

One or more errors occurred. (microsoft.net.workload.mono.toolchain.manifest-6.0.300.msi.x64::6.0.5 not found in NuGet https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-runtime-323bf2dd/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-emsdk-572aeedc/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json;https://api.nuget.org/v3/index.json.

**Comment by Clancey** [comment]
Here is the command, I use on CI:   https://github.com/dotnet/Comet/blob/dev/.github/workflows/dev.yml#L51-L58

**Comment by JbmOnGitHub** [comment]
Thank you, I stay tuned for this great project. I imagine things will be easier when MAUI is stabilized!
