### ISSUE TITLE
Text doesn't update properly

### ISSUE THREAD

**Issue by ziaulhasanhamim** [dotnet/Comet#251]
```c#
new VStack()
{
    new TextField(state.FirstName, "First Name"),
    new TextField(state.LastName, "Last Name"),
    new Text(() => $"{state.FirstName} {state.LastName}")
}
```
By default FirstName and LastName is empty. When They are changed via TextField only one letter Shows up in new `Text(() => $"{state.FirstName} {state.LastName}")`. I'm very new to comet. Also I can't find docs for `TextField`. So there might be something i'm doing wrong there

**Comment by Clancey** [comment]
My guess is a laytout bug. Try  ```new Text(() => $"{state.FirstName} {state.LastName}").FillHorizontal()```

**Comment by ziaulhasanhamim** [comment]
yeah working that way. So is it a bug that will be fixed in the future? Or this is the way to do it?

**Comment by Clancey** [comment]
Will be fixed in a future release!
