### ISSUE TITLE
Template versioning

### ISSUE THREAD

**Issue by vvolkgang** [dotnet/Comet#256]
Not sure if this is an actual issue / if you're aware, just letting you know.

1. The template [versioning](https://www.nuget.org/packages/Clancey.Comet.Templates.Multiplatform) went from `0.3.80-beta` to `0.3.335-beta` some months ago
2. If you `dotnet new --install Clancey.Comet.Templates.Multiplatform` (without specifying a version) it will install `0.3.45-beta` which isn't the latest, but running `dotnet new --update-check` shows the correct latest version

**Comment by teejay-87** [comment]
You just saved my day. Just letting you know.
